# Generated by Django 2.1.7 on 2019-03-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesuplead',
            name='notes_file',
            field=models.FileField(blank=True, null=True, upload_to='Notes/universitynotes/'),
        ),
    ]
