# Generated by Django 2.1.7 on 2019-03-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notesuplead_notes_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotesUplead',
            new_name='NotesUpload',
        ),
    ]
