# Generated by Django 2.1.7 on 2019-03-17 08:15

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmissionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=254, null=True)),
                ('admission_number', models.CharField(blank=True, max_length=254, null=True)),
                ('university', models.CharField(blank=True, max_length=254, null=True)),
                ('username', models.CharField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=254, null=True)),
                ('type_of_assignment', models.CharField(blank=True, max_length=254, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=254, null=True)),
                ('is_marked', models.BooleanField(blank=True, default=False, null=True)),
                ('file_name', models.FileField(blank=True, null=True, upload_to='documents/studentsassignments/')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='AssinmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_assignment', models.CharField(blank=True, max_length=254, null=True)),
                ('assignment_title', models.TextField(blank=True, max_length=254, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=254, null=True)),
                ('unit_code', models.CharField(blank=True, max_length=254, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='assignmentsubmissionform',
            name='AssinmentType',
            field=models.ManyToManyField(to='assignments.AssinmentType'),
        ),
        migrations.AddField(
            model_name='assignmentsubmissionform',
            name='accounts',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
