# Generated by Django 2.1.7 on 2019-03-15 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmissionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('admission_number', models.CharField(max_length=30)),
                ('university', models.CharField(max_length=30)),
                ('file_name', models.FileField(upload_to='')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
