# Generated by Django 2.1.7 on 2019-03-16 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmissionform',
            name='accounts',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
