# Generated by Django 2.1.7 on 2019-03-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_auto_20190316_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmissionform',
            name='admission_number',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmissionform',
            name='full_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmissionform',
            name='phone_number',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmissionform',
            name='university',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmissionform',
            name='username',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmissionform',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='documents/studentsassignments/'),
        ),
    ]
