# Generated by Django 2.1.7 on 2019-03-16 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_auto_20190316_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=254)),
                ('assignment_title', models.CharField(max_length=254)),
                ('unit_code', models.CharField(max_length=254)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='assignmentsubmissionform',
            name='assignment_type',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmissionform',
            name='assinmenttype',
            field=models.ManyToManyField(to='assignments.AssinmentType'),
        ),
    ]
