# Generated by Django 2.1.7 on 2019-03-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_auto_20190316_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinmenttype',
            name='unit_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
