# Generated by Django 2.1.7 on 2019-03-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_assinmenttype_unit_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assinmenttype',
            old_name='type_name',
            new_name='type_of_assignment',
        ),
    ]
