# Generated by Django 2.1.7 on 2019-03-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_auto_20190316_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinmenttype',
            name='assignment_title',
            field=models.TextField(),
        ),
    ]
