# Generated by Django 2.1.7 on 2019-03-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_auto_20190316_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentsubmissionform',
            old_name='assinment_type',
            new_name='AssinmentType',
        ),
    ]
